---
deployment:
  tasks:
    - export DEPLOYPATH=/home/u1665670/public_html/fashafadillah.xyz
    - /bin/cp -R node_modules $DEPLOYPAT
    - /bin/cp -R public $DEPLOYPAT
    - /bin/cp -R src $DEPLOYPAT
    - /bin/cp package-lock.json $DEPLOYPATH
    - /bin/cp package.json $DEPLOYPATH
    - /bin/cp README.md $DEPLOYPATH
